// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: options.proto

package com.netease.protocGenAs3;

public final class Options {
  private Options() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.netease.protocGenAs3.Options.as3Bindable);
    registry.add(com.netease.protocGenAs3.Options.as3AmfAlias);
    registry.add(com.netease.protocGenAs3.Options.as3AmfAutoAlias);
    registry.add(com.netease.protocGenAs3.Options.as3ClientSideService);
    registry.add(com.netease.protocGenAs3.Options.as3ServerSideService);
  }
  public static final int AS3_BINDABLE_FIELD_NUMBER = 9393;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> as3Bindable = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int AS3_AMF_ALIAS_FIELD_NUMBER = 9394;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> as3AmfAlias = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int AS3_AMF_AUTO_ALIAS_FIELD_NUMBER = 9395;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> as3AmfAutoAlias = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int AS3_CLIENT_SIDE_SERVICE_FIELD_NUMBER = 9396;
  /**
   * <code>extend .google.protobuf.ServiceOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      java.lang.Boolean> as3ClientSideService = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int AS3_SERVER_SIDE_SERVICE_FIELD_NUMBER = 9397;
  /**
   * <code>extend .google.protobuf.ServiceOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      java.lang.Boolean> as3ServerSideService = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\roptions.proto\032 google/protobuf/descrip" +
      "tor.proto:=\n\014as3_bindable\022\037.google.proto" +
      "buf.MessageOptions\030\261I \001(\010:\005false:7\n\ras3_" +
      "amf_alias\022\037.google.protobuf.MessageOptio" +
      "ns\030\262I \001(\t:C\n\022as3_amf_auto_alias\022\037.google" +
      ".protobuf.MessageOptions\030\263I \001(\010:\005false:G" +
      "\n\027as3_client_side_service\022\037.google.proto" +
      "buf.ServiceOptions\030\264I \001(\010:\004true:H\n\027as3_s" +
      "erver_side_service\022\037.google.protobuf.Ser" +
      "viceOptions\030\265I \001(\010:\005falseB\032\n\030com.netease",
      ".protocGenAs3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    as3Bindable.internalInit(descriptor.getExtensions().get(0));
    as3AmfAlias.internalInit(descriptor.getExtensions().get(1));
    as3AmfAutoAlias.internalInit(descriptor.getExtensions().get(2));
    as3ClientSideService.internalInit(descriptor.getExtensions().get(3));
    as3ServerSideService.internalInit(descriptor.getExtensions().get(4));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
